"""add labels and created_at to tasks

Revision ID: ef1e5e738c26
Revises: 6e8d20cb5aab
Create Date: 2026-07-10 12:32:30.288400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1e5e738c26'
down_revision: Union[str, Sequence[str], None] = '6e8d20cb5aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('labels', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'labels')
    # ### end Alembic commands ###
